pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'eu-west-1'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker sanity check') {
            steps {
                sh '''
                    echo "=== Docker version ==="
                    docker --version
        
                    echo "=== Docker info ==="
                    docker ps
                '''
            }
        }

        
        stage('Build Docker image') {
            steps {
                sh '''
                    docker build -t fire-tests .
                '''
            }
        }

        stage('Run tests') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                    string(credentialsId: 'S3_BUCKET_NAME', variable: 'S3_BUCKET_NAME')
                ]) {
                    sh '''
                        mkdir -p pytest-reports
        
                        docker run --rm \
                          -e CI=true \
                          -e AWS_ACCESS_KEY_ID \
                          -e AWS_SECRET_ACCESS_KEY \
                          -e AWS_DEFAULT_REGION \
                          -e S3_BUCKET_NAME \
                          -v "$WORKSPACE/pytest-reports:/app/pytest-reports" \
                          fire-tests \
                          pytest tests/ --junitxml=/app/pytest-reports/pytest-report.xml
                    '''
                }
            }
        }

    post {
        always {
            junit 'pytest-reports/pytest-report.xml'
        }
        failure {
            echo '❌ Tests échoués'
        }
        success {
            echo '✅ Tests OK'
        }
    }
}
